name: Deploy Docs to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
<<<<<<< HEAD
	  pip install sphinx-copybutton
=======
          pip install sphinx-copybutton
>>>>>>> 184076fae0e6d7555c20a47f35ad380baeddfe2e
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          lfs: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
